// <auto-generated />
namespace Store.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class discount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(discount));
        
        string IMigrationMetadata.Id
        {
            get { return "201603101207447_discount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
